-- Seed: 001_subscription_plans
-- Description: Insert default subscription plans
-- Created: 2026-02-01

INSERT INTO subscription_plans (
    id,
    name,
    slug,
    description,
    price,
    currency,
    duration,
    status,
    active_request_limit,
    graphics_credits,
    video_credits,
    web_credits,
    turnaround_hours,
    features,
    is_featured,
    display_order
) VALUES
(
    uuid_generate_v4(),
    'Startup',
    'startup',
    'Perfect for startups and small businesses needing consistent design support',
    599.00,
    'INR',
    'weekly',
    'active',
    1,
    5,
    0,
    0,
    48,
    '["5 digital graphic posters", "48-hour turnaround", "Unlimited revisions", "Dedicated designer", "Brand guidelines support"]'::jsonb,
    false,
    1
),
(
    uuid_generate_v4(),
    'Standard',
    'standard',
    'Ideal for growing businesses with regular design and video needs',
    2999.00,
    'INR',
    'monthly',
    'active',
    2,
    28,
    4,
    0,
    48,
    '["28 graphics per month", "4 short videos", "2 active requests", "48-hour turnaround", "Unlimited revisions", "Priority support", "Brand kit access"]'::jsonb,
    true,
    2
),
(
    uuid_generate_v4(),
    'Business',
    'business',
    'Complete creative solution for established businesses and agencies',
    9999.00,
    'INR',
    'monthly',
    'active',
    3,
    90,
    4,
    1,
    24,
    '["90 social media posters", "4 YouTube videos", "1 website project", "3 active requests", "24-hour turnaround", "Unlimited revisions", "Dedicated account manager", "Priority support", "Advanced analytics"]'::jsonb,
    true,
    3
),
(
    uuid_generate_v4(),
    'Enterprise',
    'enterprise',
    'Custom solution for large organizations with dedicated team',
    0.00,
    'INR',
    'monthly',
    'active',
    10,
    0,
    0,
    0,
    12,
    '["Unlimited requests", "Dedicated design team", "12-hour turnaround", "Custom SLA", "API access", "White-label option", "Dedicated account manager", "24/7 support"]'::jsonb,
    false,
    4
);

-- Add quarterly and yearly variants for Standard plan
INSERT INTO subscription_plans (
    id,
    name,
    slug,
    description,
    price,
    currency,
    duration,
    status,
    active_request_limit,
    graphics_credits,
    video_credits,
    web_credits,
    turnaround_hours,
    features,
    is_featured,
    display_order
) VALUES
(
    uuid_generate_v4(),
    'Standard Quarterly',
    'standard-quarterly',
    'Standard plan billed quarterly with 10% discount',
    8097.00,
    'INR',
    'quarterly',
    'active',
    2,
    84,
    12,
    0,
    48,
    '["84 graphics per quarter", "12 short videos", "2 active requests", "48-hour turnaround", "Unlimited revisions", "Priority support", "Brand kit access", "10% savings"]'::jsonb,
    false,
    5
),
(
    uuid_generate_v4(),
    'Standard Yearly',
    'standard-yearly',
    'Standard plan billed yearly with 20% discount',
    28788.00,
    'INR',
    'yearly',
    'active',
    2,
    336,
    48,
    0,
    48,
    '["336 graphics per year", "48 short videos", "2 active requests", "48-hour turnaround", "Unlimited revisions", "Priority support", "Brand kit access", "20% savings"]'::jsonb,
    false,
    6
);
