-- Migration: 012_create_request_activities_table
-- Description: Create request activities table for audit trail
-- Created: 2026-02-01

CREATE TYPE activity_type AS ENUM (
    'created', 'assigned', 'reassigned', 'started', 'file_uploaded',
    'submitted_for_review', 'approved_by_manager', 'rejected_by_manager',
    'sent_to_client', 'feedback_received', 'revision_requested',
    'approved_by_client', 'completed', 'cancelled', 'priority_changed',
    'deadline_extended'
);

CREATE TABLE request_activities (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    request_id UUID NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_type activity_type NOT NULL,
    description TEXT,
    metadata JSONB,
    is_system_generated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX idx_request_activities_request_id ON request_activities(request_id);
CREATE INDEX idx_request_activities_user_id ON request_activities(user_id);
CREATE INDEX idx_request_activities_activity_type ON request_activities(activity_type);
CREATE INDEX idx_request_activities_created_at ON request_activities(created_at);
CREATE INDEX idx_request_activities_request_created ON request_activities(request_id, created_at);

-- Trigger for updated_at
CREATE TRIGGER update_request_activities_updated_at BEFORE UPDATE ON request_activities
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE request_activities IS 'Activity timeline and audit trail for requests';
COMMENT ON COLUMN request_activities.metadata IS 'Additional activity details like old/new values, file IDs';
COMMENT ON COLUMN request_activities.is_system_generated IS 'True if activity was automatically generated by system';
